plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.5'
}

group = artifactGroup
version = "$artifactVersion" + (isSnapshot.equals('Y') ? '-SNAPSHOT' : '')

java {
    sourceCompatibility = JavaVersion.VERSION_25
}

repositories {
    mavenCentral()
}

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:4.0.5')
    testImplementation platform('org.springframework.boot:spring-boot-dependencies:4.0.5')

    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-restclient'
    implementation 'org.apache.commons:commons-csv:1.14.1'
    implementation 'io.github.wimdeblauwe:error-handling-spring-boot-starter:5.1.1'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.1'
    compileOnly 'org.projectlombok:lombok:1.18.44'
    annotationProcessor 'org.projectlombok:lombok:1.18.44'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
    useJUnitPlatform()
}
